project:
  type: book
  output-dir: docs

book:
  title: "地理資訊系統概論"
  author: "Cheng-Tao Lin"
  cover-image: images/bookcover.png
  date: "2022-07-09"
  favicon: images/gisfavicon.png
  page-navigation: true
  language: zh
  number-depth: 2
  repo-url: https://github.com/mutolisp/introGIS
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub, docx]
  sharing: [facebook, twitter]

  chapters:
    - index.qmd
    - intro.qmd
    - crs.qmd
    - vector.qmd
    - raster.qmd
    - part: introQGIS.qmd
      chapters:
      - useQGIS.qmd
      - QGIS_projects.qmd
      - webResources.qmd
      - vector_selection.qmd
    - part: QGIS_export_map.qmd
    - part: QGIS_vector_analysis.qmd
    - part: QGIS_raster_analysis.qmd
    - part: QGIS_image_processing.qmd
      chapters:
      - QGIS_georeference.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex 
    code-copy: true
    fig-responsive: true
    citations-hover: true
    comment-hover: true
  pdf:
    header-includes:
      - \usepackage{fontspec} # 使用 fontspec package
      - \usepackage{xeCJK}    # 使用 xeCJK package
      - \setCJKmainfont{Songti TC}
    documentclass: scrreprt
  epub:
    css: epub-styles.css
