project:
  type: book
  output-dir: docs

book:
  title: "地理資訊系統概論"
  author: "Cheng-Tao Lin"
  date: "2022-07-09"
  number-depth: 2
  repo-url: https://github.com/mutolisp/introGIS
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub, docx]
  sharing: [facebook, twitter]
  sidebar:
    style: docked
  chapters:
    - index.qmd
    - intro.qmd
    - crs.qmd
    - useQGIS.qmd
    - vector.qmd
    - raster.qmd
    - webResources.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lumen
  pdf:
    documentclass: scrreprt



